# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20171010_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='sportage', max_length=30),
            preserve_default=False,
        ),
    ]
